### PR TITLE
Fix broken UI on Windows

### LINKED ISSUE #29: "filter by tag" ui is broken on windows
image
image

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`

### PR DESCRIPTION
**Pull request by SimYunSup**
Fix #29.
image

### CODE REVIEW

**Review by disjukr — APPROVED** [review]

**Comment by tmm1** [comment]
Would be nice to get a new release on chrome store with this fix.

**Comment by disjukr** [comment]
@tmm1 Hello, I haven't been able to maintain pbkit and its surrounding tools lately because I've been working on another project.
Although I did find a [new maintainer](https://github.com/pbkit/pbkit/issues/307), it seems like he's also too busy to take care of pbkit-devtools.

If it's just a matter of packaging and re-uploading, I could try to make some time for it, but recently [Chrome dropped support for Manifest V2](https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline), so I think we need to [resolve that](https://github.com/pbkit/pbkit-devtools/issues/12) first before an update is possible.

If you have time, could you take care of this issue instead? Then I'll try repackaging and uploading it to the store again.

**Comment by disjukr** [comment]
Also, I'm really curious how you came to use this extension.
Would it be possible to know which project is using pbkit and pbkit devtools?

**Comment by cometkim** [comment]
I will start working on right after a trip. Maybe in the middle of this month

**Comment by cometkim** [comment]
However, devtools and integrations may delayed, consolidating the core is higher priority

**Pull request merged**
