### PR TITLE
feat(filter): Implement filter feature

### PR DESCRIPTION
**Pull request by hyp3rflow**
image

part of #16

### CODE REVIEW

**Comment by disjukr** [comment]
🤔  That UI looks like it should be filtered by RPC method name.

**Comment by disjukr** [comment]
There should be a search bar with a magnifying glass icon on the right tab to feel like searching in the request/response payload.

**Comment by hyp3rflow** [comment]
@disjukr I think the searching on both `RequestList` and `RequestDetail` by req/res payload is good when finding where comes certain value or response. If you think this is unnecessary, how about separating it? like Including Req/Res feature or the Real `Search` feature.

> There should be a search bar with a magnifying glass icon on the right tab to feel like searching in the request/response payload.
I'll implement the `DetailSearch` feature for search request or response payload on the `RequestDetail` section.

**Comment by hyp3rflow** [comment]
@disjukr I changed for the filter to check only servicePath and rpcName. looks good to you?

**Review by disjukr — APPROVED** [review]

**Pull request merged**
